version: "3.8"

services:
   backend:
      build:
         context: ./fli-guide-backend
      container_name: fli-backend
      ports:
         - "5025:5025"
      environment:
         NODE_ENV: production
      env_file:
         - ./fli-guide-backend/.env
      volumes:
         - ./fli-guide-backend:/app # Mount source code
         - /app/node_modules # Prevent host overwrite of node_modules
      depends_on:
         - db

   frontend:
      build:
         context: ./fli-guide-react
      container_name: fli-guide-v3-frontend
      ports:
         - "5173:80" # Served via nginx from port 80 in container
      depends_on:
         - backend

   db:
      image: mysql:8
      container_name: fli-guide-v3-db-1
      environment:
         MYSQL_ROOT_PASSWORD: password # Change this to match .env
         MYSQL_DATABASE: fli_db
      ports:
         - "3307:3306"
      volumes:
         - mysql_data:/var/lib/mysql

volumes:
   mysql_data:
